### ISSUE TITLE
Warning: Argument is deprecated

### ISSUE THREAD

**Issue by Inmaan** [sculley/terraform-aws-budgets-alerts#1]
│ Warning: Argument is deprecated
│
│   with module.aws_budgets_monthly_alert.random_string.random,
│   on .terraform\modules\aws_budgets_monthly_alert\main.tf line 7, in resource "random_string" "random":
│    7:   number = false
│
│ Use numeric instead.
│
│ (and one more similar warning elsewhere)

Terraform v1.2.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/random v3.3.2

**Comment by sculley** [comment]
@Inmaan - Thanks for notifying me about the deprecation warning in the `random_string` provider.

I have pushed the changes, and awaiting confirmation of tests but expect to push a new version (1.0.2) later today.

**Comment by sculley** [comment]
@Inmaan - Changes have been applied, the module has been updated to v1.0.2.

Thanks for reporting!
