### ISSUE TITLE
Blocks of type "cost_filter" are not expected here.

### ISSUE THREAD

**Issue by Inmaan** [sculley/terraform-aws-budgets-alerts#3]
After updating to v1.0.2 was getting the following error 

```
│ Error: Unsupported block type
│
│   on .terraform\modules\budgets-alerts\main.tf line 72, in resource "aws_budgets_budget" "service_budget_cost_email_notification":
│   72:   cost_filter {
│
│ Blocks of type "cost_filter" are not expected here.
```

Terraform v1.2.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/random v3.3.2

**Comment by sculley** [comment]
@Inmaan - Thanks for reporting, the `aws_budgets_budget` resource was updated in the `3.52.0` release of the AWS provider, to resolve the error you will need to update your AWS provider I'm afraid.

I forgot to set the new required version in (`v1.0.2`) and I am adding a new tag/release (`v1.0.3`) to add a version constraint/requirement to the module to request that version (`3.52.0`) of the AWS provider be installed.

**Comment by sculley** [comment]
https://github.com/sculley/terraform-aws-budgets-alerts/releases/tag/v1.0.3

**Comment by Inmaan** [comment]
> @Inmaan - Thanks for reporting, the `aws_budgets_budget` resource was updated in the `3.52.0` release of the AWS provider, to resolve the error you will need to update your AWS provider I'm afraid.
> 
> I forgot to set the new required version in (`v1.0.2`) and I am adding a new tag/release (`v1.0.3`) to add a version constraint/requirement to the module to request that version (`3.52.0`) of the AWS provider be installed.

Awesome, thank you and great work here!
